export const LAST_SAVE_TIME = 'last_save_time'
export const IS_POSTPONE = 'is_postpone'
export const BALLOON_KEYS = 'balloon.keys'
export const BALLOON = 'balloon.'
export const SUB_KEYS = 'sub.keys'
export const SUB = 'sub.'
