export const TEMP_IDS = 'TEMP:IDS'
export const TEMP_CURRENT_PAGE = 'TEMP:CURRENT_PAGE'
export const TEMP_START_TIME = 'TEMP:START_TIME'
export const TEMP_GETTING_DATA = 'TEMP:GETTING_DATA'
export const TEMP_COUNT = 'TEMP:COUNT:'
export const TEMP_NICKNAME = 'TEMP:NICKNAME:'

export const BALLOON_DATA = 'BALLOON:DATA'
export const BALLOON_HAS_DATA = 'BALLOON:HAS_DATA'
